#include <stdio.h>
#include <stdlib.h>

#include "fitsio.h"

// Declare the ffesum function


int main() {
    
    unsigned long sum = 0x1234567812345678; // Example checksum value
    int complm = 1; // Example complement flag
    char ascii_output[17]; // Buffer for the ASCII output

    // Call ffesum
    ffesum(sum, complm, ascii_output);
   
    // Output the ASCII result to stdout
    if (ascii_output) {
        printf("%s\n", ascii_output);
        // free(ascii_output); // Free the allocated memory
    } else {
        fprintf(stderr, "No output generated by ffesum\n");
    }

    return 0;
}
