#![allow(deprecated)]
#![allow(unused_imports)]

use crate::c_types::{c_char, c_int};

pub use crate::{
    buffers::*, cfileio::*, checksum::*, editcol::*, edithdu::*, eval_f::*, fitscore::*, fitsio::*,
    getcol::*, getcolb::*, getcold::*, getcole::*, getcoli::*, getcolj::*, getcolk::*, getcoll::*,
    getcols::*, getcolsb::*, getcolui::*, getcoluj::*, getcoluk::*, getkey::*, modkey::*,
    putcol::*, putcolb::*, putcold::*, putcole::*, putcoli::*, putcolj::*, putcolk::*, putcoll::*,
    putcols::*, putcolsb::*, putcolu::*, putcolui::*, putcoluj::*, putcoluk::*, putkey::*,
    scalnull::*, wcssub::*, wcsutil::*,
};

/*
   use the following special macro to test that the fitsio.h include file
   that was used to build the CFITSIO library is compatible with the version
   as included when compiling the application program
*/
#[cfg_attr(not(test), unsafe(no_mangle), deprecated)]
pub unsafe extern "C" fn fits_open_file(
    A: *mut Option<Box<fitsfile>>,
    B: *const c_char,
    C: c_int,
    D: *mut c_int,
) -> c_int {
    unsafe { ffopentest(CFITSIO_SONAME as c_int, A, B, C, D) }
}

pub(crate) mod not_safe {
    pub(crate) use super::*;
    pub(crate) use ffbnfmll as fits_binary_tformll;
    pub(crate) use ffcalc as fits_calculator;
    pub(crate) use ffcalc_rng as fits_calculator_rng;
    pub(crate) use ffclos as fits_close_file;
    pub(crate) use ffcnvthdr2str as fits_convert_hdr2str;
    pub(crate) use ffdelt as fits_delete_file;
    pub(crate) use ffdkinit as fits_create_diskfil;
    pub(crate) use ffdkopn as fits_open_diskfile;
    pub(crate) use ffdopn as fits_open_data;
    pub(crate) use ffdstr as fits_delete_str;
    pub(crate) use ffdsum as fits_decode_chksum;
    pub(crate) use ffeopn as fits_open_extlist;
    pub(crate) use ffexist as fits_file_exists;
    pub(crate) use ffextn as fits_parse_extnum;
    pub(crate) use ffexts as fits_parse_extspec;
    pub(crate) use ffffrw as fits_find_first_row;
    pub(crate) use ffflmd as fits_file_mode;
    pub(crate) use ffflnm as fits_file_name;
    pub(crate) use fffree as fits_free_memory;
    pub(crate) use fffrow as fits_find_rows;
    pub(crate) use ffg2db as fits_read_2d_byt;
    pub(crate) use ffg2dd as fits_read_2d_dbl;
    pub(crate) use ffg2de as fits_read_2d_flt;
    pub(crate) use ffg2di as fits_read_2d_sht;
    pub(crate) use ffg2dj as fits_read_2d_lng;
    pub(crate) use ffg2djj as fits_read_2d_lnglng;
    pub(crate) use ffg2dk as fits_read_2d_int;
    pub(crate) use ffg2dsb as fits_read_2d_sbyt;
    pub(crate) use ffg2dui as fits_read_2d_usht;
    pub(crate) use ffg2duj as fits_read_2d_ulng;
    pub(crate) use ffg2dujj as fits_read_2d_ulnglng;
    pub(crate) use ffg2duk as fits_read_2d_uint;
    pub(crate) use ffgacl as fits_get_acolparms;
    pub(crate) use ffgcfb as fits_read_colnull_byt;
    pub(crate) use ffgcfd as fits_read_colnull_dbl;
    pub(crate) use ffgcfe as fits_read_colnull_flt;
    pub(crate) use ffgcfi as fits_read_colnull_sht;
    pub(crate) use ffgcfj as fits_read_colnull_lng;
    pub(crate) use ffgcfk as fits_read_colnull_int;
    pub(crate) use ffgcfl as fits_read_colnull_log;
    pub(crate) use ffgcfs as fits_read_colnull_str;
    pub(crate) use ffgcfsb as fits_read_colnull_sbyt;
    pub(crate) use ffgcfui as fits_read_colnull_usht;
    pub(crate) use ffgcfuj as fits_read_colnull_ulng;
    pub(crate) use ffgcfuk as fits_read_colnull_uint;
    pub(crate) use ffgcve as fits_read_col_flt;
    pub(crate) use ffgcvi as fits_read_col_sht;
    pub(crate) use ffgcvj as fits_read_col_lng;
    pub(crate) use ffgcvk as fits_read_col_int;
    pub(crate) use ffgcvsb as fits_read_col_sbyt;
    pub(crate) use ffgcvui as fits_read_col_usht;
    pub(crate) use ffgcvuj as fits_read_col_ulng;
    pub(crate) use ffgcvuk as fits_read_col_uint;
    pub(crate) use ffgdessll as fits_read_descriptsl;
    pub(crate) use ffggpb as fits_read_grppar_byt;
    pub(crate) use ffggpd as fits_read_grppar_dbl;
    pub(crate) use ffggpe as fits_read_grppar_flt;
    pub(crate) use ffggpi as fits_read_grppar_sht;
    pub(crate) use ffggpj as fits_read_grppar_lng;
    pub(crate) use ffggpjj as fits_read_grppar_lnglng;
    pub(crate) use ffggpk as fits_read_grppar_int;
    pub(crate) use ffggpsb as fits_read_grppar_sbyt;
    pub(crate) use ffggpui as fits_read_grppar_usht;
    pub(crate) use ffggpuj as fits_read_grppar_ulng;
    pub(crate) use ffggpujj as fits_read_grppar_ulnglng;
    pub(crate) use ffggpuk as fits_read_grppar_uint;
    pub(crate) use ffghad as fits_get_hduaddr;
    pub(crate) use ffghbn as fits_read_btblhdr;
    pub(crate) use ffghbnll as fits_read_btblhdrll;
    pub(crate) use ffghof as fits_get_hduoff;
    pub(crate) use ffghpr as fits_read_imghdr;
    pub(crate) use ffghtb as fits_read_atblhdr;
    pub(crate) use ffghtbll as fits_read_atblhdrll;
    pub(crate) use ffgiet as fits_get_img_equivtype;
    pub(crate) use ffgiprll as fits_get_img_paramll;
    pub(crate) use ffgiwcs as fits_get_image_wcs_key;
    pub(crate) use ffgkcl as fits_get_keyclass;
    pub(crate) use ffgkcsl as fits_get_key_com_strlen;
    pub(crate) use ffgkls as fits_read_key_longstr;
    pub(crate) use ffgknd as fits_read_keys_dbl;
    pub(crate) use ffgkne as fits_read_keys_flt;
    pub(crate) use ffgknl as fits_read_keys_log;
    pub(crate) use ffgksl as fits_get_key_strlen;
    pub(crate) use ffgkyt as fits_read_key_triple;
    pub(crate) use ffgnxk as fits_find_nextkey;
    pub(crate) use ffgpf as fits_read_imgnull;
    pub(crate) use ffgpv as fits_read_img;
    pub(crate) use ffgpxf as fits_read_pixnull;
    pub(crate) use ffgsfb as fits_read_subsetnull_by;
    pub(crate) use ffgsfd as fits_read_subsetnull_db;
    pub(crate) use ffgsfe as fits_read_subsetnull_fl;
    pub(crate) use ffgsfi as fits_read_subsetnull_sh;
    pub(crate) use ffgsfj as fits_read_subsetnull_ln;
    pub(crate) use ffgsfjj as fits_read_subsetnull_lngln;
    pub(crate) use ffgsfk as fits_read_subsetnull_in;
    pub(crate) use ffgsfsb as fits_read_subsetnull_sby;
    pub(crate) use ffgsfui as fits_read_subsetnull_ush;
    pub(crate) use ffgsfuj as fits_read_subsetnull_uln;
    pub(crate) use ffgsfujj as fits_read_subsetnull_ulngln;
    pub(crate) use ffgsfuk as fits_read_subsetnull_uin;
    pub(crate) use ffgsky as fits_read_string_key;
    pub(crate) use ffgskyc as fits_read_string_key_com;
    pub(crate) use ffgstr as fits_read_str;
    pub(crate) use ffgsv as fits_read_subset;
    pub(crate) use ffgtcs as fits_read_tbl_coor;
    pub(crate) use ffgtdmll as fits_read_tdimll;
    pub(crate) use ffgtmo as fits_get_timeout;
    pub(crate) use ffgtwcs as fits_get_table_wcs_key;
    pub(crate) use ffgunt as fits_read_key_unit;
    pub(crate) use ffibin as fits_insert_btbl;
    pub(crate) use ffifile as fits_parse_input_filename;
    pub(crate) use ffikfc as fits_insert_key_fixcm;
    pub(crate) use ffikfm as fits_insert_key_fixdblcm;
    pub(crate) use ffikls as fits_insert_key_longstr;
    pub(crate) use ffikyc as fits_insert_key_cmp;
    pub(crate) use ffikyd as fits_insert_key_dbl;
    pub(crate) use ffikye as fits_insert_key_flt;
    pub(crate) use ffikyf as fits_insert_key_fixfl;
    pub(crate) use ffikyg as fits_insert_key_fixdb;
    pub(crate) use ffikyl as fits_insert_key_log;
    pub(crate) use ffikym as fits_insert_key_dblcm;
    pub(crate) use ffikys as fits_insert_key_str;
    pub(crate) use ffikyu as fits_insert_key_null;
    pub(crate) use ffimem as fits_create_memfil;
    pub(crate) use ffinttyp as fits_get_inttype;
    pub(crate) use ffiopn as fits_open_image;
    pub(crate) use ffitab as fits_insert_atbl;
    pub(crate) use ffiter as fits_iterate_data;
    pub(crate) use ffiurl as fits_parse_input_url;
    pub(crate) use ffmkyuj as fits_modify_key_ulng;
    pub(crate) use ffnchk as fits_null_check;
    pub(crate) use ffomem as fits_open_memfile;
    pub(crate) use ffpcks as fits_write_chksum;
    pub(crate) use ffpdat as fits_write_date;
    pub(crate) use ffpdes_safe as fits_write_descript;
    pub(crate) use ffphbn as fits_write_btblhdr;
    pub(crate) use ffphtb as fits_write_atblhdr;
    pub(crate) use ffpknd as fits_write_keys_dbl;
    pub(crate) use ffpkne as fits_write_keys_flt;
    pub(crate) use ffpknf as fits_write_keys_fixflt;
    pub(crate) use ffpkng as fits_write_keys_fixdbl;
    pub(crate) use ffpknj as fits_write_keys_lng;
    pub(crate) use ffpknl as fits_write_keys_log;
    pub(crate) use ffpkns as fits_write_keys_str;
    pub(crate) use ffpktp as fits_write_key_templat;
    pub(crate) use ffpkyt as fits_write_key_triple;
    pub(crate) use ffplsw as fits_write_key_longwar;
    pub(crate) use ffpnul as fits_set_imgnull;
    pub(crate) use ffppxn as fits_write_pixnull;
    pub(crate) use ffppxnll as fits_write_pixnullll;
    pub(crate) use ffptdm as fits_write_tdim;
    pub(crate) use ffpthp as fits_write_theap;
    pub(crate) use ffpunt as fits_write_key_unit;
    pub(crate) use ffreopen as fits_reopen_file;
    pub(crate) use ffrprt as fits_report_error;
    pub(crate) use ffrtnm as fits_parse_rootname;
    pub(crate) use ffsnul as fits_set_atblnull;
    pub(crate) use ffstmo as fits_set_timeout;
    pub(crate) use ffthdu as fits_get_num_hdus;
    pub(crate) use fftnul as fits_set_btblnull;
    pub(crate) use fftopn as fits_open_table;
    pub(crate) use fftplt as fits_create_templat;
    pub(crate) use ffukyuj as fits_update_key_ulng;
    pub(crate) use ffupck as fits_update_chksum;
    pub(crate) use ffurlt as fits_url_type;
    pub(crate) use ffvers as fits_get_version;
    pub(crate) use ffwldp as fits_pix_to_worl;
    pub(crate) use ffwrhdu as fits_write_hdu;
    pub(crate) use ffxypx as fits_world_to_pi;
    pub(crate) use fits_copy_image_section as ffcpim;
}

#[deny(unsafe_code, unsafe_op_in_unsafe_fn, deprecated)]
pub(crate) mod safer {
    pub use super::*;

    pub(crate) use ffasfm_safe as fits_ascii_tform;
    pub(crate) use ffbnfm_safe as fits_binary_tform;
    pub(crate) use ffccls_safe as fits_copy_cols;
    pub(crate) use ffcmph_safer as fits_compress_heap;
    pub(crate) use ffcmrk_safe as fits_clear_errmark;
    pub(crate) use ffcmsg_safe as fits_clear_errmsg;
    pub(crate) use ffcopy_safer as fits_copy_hdu;
    pub(crate) use ffcpcl_safe as fits_copy_col;
    pub(crate) use ffcpdt_safe as fits_copy_data;
    pub(crate) use ffcpfl_safer as fits_copy_file;
    pub(crate) use ffcphd_safer as fits_copy_header;
    pub(crate) use ffcpht_safer as fits_copy_hdutab;
    pub(crate) use ffcpky_safe as fits_copy_key;
    pub(crate) use ffcprw_safe as fits_copy_rows;
    pub(crate) use ffcrhd_safer as fits_create_hdu;
    pub(crate) use ffcrim_safer as fits_create_img;
    pub(crate) use ffcrimll_safer as fits_create_imgll;
    pub(crate) use ffcrtb_safer as fits_create_tbl;
    pub(crate) use ffdcol_safe as fits_delete_col;
    pub(crate) use ffdhdu_safer as fits_delete_hdu;
    pub(crate) use ffdkey_safe as fits_delete_key;
    pub(crate) use ffdrec_safe as fits_delete_record;
    pub(crate) use ffdrow_safe as fits_delete_rows;
    pub(crate) use ffdrrg_safe as fits_delete_rowrang;
    pub(crate) use ffdrws_safe as fits_delete_rowlis;
    pub(crate) use ffdrwsll_safe as fits_delete_rowlistl;
    pub(crate) use ffdtdm_safe as fits_decode_tdim;
    pub(crate) use ffdtdmll_safe as fits_decode_tdimll;
    pub(crate) use ffeqty_safe as fits_get_eqcoltype;
    pub(crate) use ffeqtyll_safe as fits_get_eqcoltypel;
    pub(crate) use ffesum_safe as fits_encode_chksum;
    pub(crate) use ffflsh_safe as fits_flush_buffer;
    pub(crate) use ffflus_safer as fits_flush_file;
    pub(crate) use ffg3db_safe as fits_read_3d_byt;
    pub(crate) use ffg3dd_safe as fits_read_3d_dbl;
    pub(crate) use ffg3de_safe as fits_read_3d_flt;
    pub(crate) use ffg3di_safe as fits_read_3d_sht;
    pub(crate) use ffg3dj_safe as fits_read_3d_lng;
    pub(crate) use ffg3djj_safe as fits_read_3d_lnglng;
    pub(crate) use ffg3dk_safe as fits_read_3d_int;
    pub(crate) use ffg3dsb_safe as fits_read_3d_sbyt;
    pub(crate) use ffg3dui_safe as fits_read_3d_usht;
    pub(crate) use ffg3duj_safe as fits_read_3d_ulng;
    pub(crate) use ffg3dujj_safe as fits_read_3d_ulnglng;
    pub(crate) use ffg3duk_safe as fits_read_3d_uint;
    pub(crate) use ffgabc_safe as fits_get_tbcol;
    pub(crate) use ffgbcl_safe as fits_get_bcolparms;
    pub(crate) use ffgbclll_safe as fits_get_bcolparmsll;
    pub(crate) use ffgcdw_safe as fits_get_col_display_width;
    pub(crate) use ffgcf_safe as fits_read_colnull;
    pub(crate) use ffgcfc_safe as fits_read_colnull_cmp;
    pub(crate) use ffgcfjj_safe as fits_read_colnull_lnglng;
    pub(crate) use ffgcfm_safe as fits_read_colnull_dblcm;
    pub(crate) use ffgcfujj_safe as fits_read_colnull_ulnglng;
    pub(crate) use ffgcks_safe as fits_get_chksum;
    pub(crate) use ffgcnn_safe as fits_get_colname;
    pub(crate) use ffgcno_safe as fits_get_colnum;
    pub(crate) use ffgcrd_safe as fits_read_card;
    pub(crate) use ffgcv_safe as fits_read_col;
    pub(crate) use ffgcvb_safe as fits_read_col_byt;
    pub(crate) use ffgcvc_safe as fits_read_col_cmp;
    pub(crate) use ffgcvd_safe as fits_read_col_dbl;
    pub(crate) use ffgcvjj_safe as fits_read_col_lnglng;
    pub(crate) use ffgcvl_safe as fits_read_col_log;
    pub(crate) use ffgcvm_safe as fits_read_col_dblcm;
    pub(crate) use ffgcvs_safe as fits_read_col_str;
    pub(crate) use ffgcvujj_safe as fits_read_col_ulnglng;
    pub(crate) use ffgcx_safe as fits_read_col_bit;
    pub(crate) use ffgdes_safe as fits_read_descript;
    pub(crate) use ffgdesll_safe as fits_read_descriptll;
    pub(crate) use ffgdess_safe as fits_read_descripts;
    pub(crate) use ffgextn as fits_read_ext;
    pub(crate) use ffghadll_safe as fits_get_hduaddrll;
    pub(crate) use ffghdt_safe as fits_get_hdu_type;
    pub(crate) use ffghprll_safe as fits_read_imghdrll;
    pub(crate) use ffgics_safe as fits_read_img_coor;
    pub(crate) use ffgicsa_safe as fits_read_img_coord_versio;
    pub(crate) use ffgidm_safe as fits_get_img_dim;
    pub(crate) use ffgidt_safe as fits_get_img_type;
    pub(crate) use ffgipr_safe as fits_get_img_param;
    pub(crate) use ffgisz_safe as fits_get_img_size;
    pub(crate) use ffgiszll_safe as fits_get_img_sizell;
    pub(crate) use ffgkey_safe as fits_read_keyword;
    pub(crate) use ffgknj_safe as fits_read_keys_lng;
    pub(crate) use ffgknjj_safe as fits_read_keys_lnglng;
    pub(crate) use ffgknm_safe as fits_get_keyname;
    pub(crate) use ffgkns_safe as fits_read_keys_str;
    pub(crate) use ffgky_safe as fits_read_key;
    pub(crate) use ffgkyc_safe as fits_read_key_cmp;
    pub(crate) use ffgkyd_safe as fits_read_key_dbl;
    pub(crate) use ffgkye_safe as fits_read_key_flt;
    pub(crate) use ffgkyj_safe as fits_read_key_lng;
    pub(crate) use ffgkyjj_safe as fits_read_key_lnglng;
    pub(crate) use ffgkyl_safe as fits_read_key_log;
    pub(crate) use ffgkym_safe as fits_read_key_dblcmp;
    pub(crate) use ffgkyn_safe as fits_read_keyn;
    pub(crate) use ffgkys_safe as fits_read_key_str;
    pub(crate) use ffgkyujj_safe as fits_read_key_ulnglng;
    pub(crate) use ffgmsg_safe as fits_read_errmsg;
    pub(crate) use ffgncl_safe as fits_get_num_cols;
    pub(crate) use ffgnrw_safe as fits_get_num_rows;
    pub(crate) use ffgnrwll_safe as fits_get_num_rowsll;
    pub(crate) use ffgpfb_safe as fits_read_imgnull_by;
    pub(crate) use ffgpfd_safe as fits_read_imgnull_db;
    pub(crate) use ffgpfe_safe as fits_read_imgnull_fl;
    pub(crate) use ffgpfi_safe as fits_read_imgnull_sh;
    pub(crate) use ffgpfj_safe as fits_read_imgnull_ln;
    pub(crate) use ffgpfjj_safe as fits_read_imgnull_lngln;
    pub(crate) use ffgpfk_safe as fits_read_imgnull_in;
    pub(crate) use ffgpfsb_safe as fits_read_imgnull_sby;
    pub(crate) use ffgpfui_safe as fits_read_imgnull_ush;
    pub(crate) use ffgpfuj_safe as fits_read_imgnull_uln;
    pub(crate) use ffgpfujj_safe as fits_read_imgnull_ulngln;
    pub(crate) use ffgpfuk_safe as fits_read_imgnull_uin;
    pub(crate) use ffgpvb_safe as fits_read_img_byt;
    pub(crate) use ffgpvd_safe as fits_read_img_dbl;
    pub(crate) use ffgpve_safe as fits_read_img_flt;
    pub(crate) use ffgpvi_safe as fits_read_img_sht;
    pub(crate) use ffgpvj_safe as fits_read_img_lng;
    pub(crate) use ffgpvjj_safe as fits_read_img_lnglng;
    pub(crate) use ffgpvk_safe as fits_read_img_int;
    pub(crate) use ffgpvsb_safe as fits_read_img_sbyt;
    pub(crate) use ffgpvui_safe as fits_read_img_usht;
    pub(crate) use ffgpvuj_safe as fits_read_img_ulng;
    pub(crate) use ffgpvujj_safe as fits_read_img_ulnglng;
    pub(crate) use ffgpvuk_safe as fits_read_img_uint;
    pub(crate) use ffgpxfll_safe as fits_read_pixnullll;
    pub(crate) use ffgpxv_safe as fits_read_pix;
    pub(crate) use ffgpxvll_safe as fits_read_pixll;
    pub(crate) use ffgrec_safe as fits_read_record;
    pub(crate) use ffgrsz_safe as fits_get_rowsize;
    pub(crate) use ffgstm_safe as fits_get_system_time;
    pub(crate) use ffgsvb_safe as fits_read_subset_byt;
    pub(crate) use ffgsvd_safe as fits_read_subset_dbl;
    pub(crate) use ffgsve_safe as fits_read_subset_flt;
    pub(crate) use ffgsvi_safe as fits_read_subset_sht;
    pub(crate) use ffgsvj_safe as fits_read_subset_lng;
    pub(crate) use ffgsvjj_safe as fits_read_subset_lnglng;
    pub(crate) use ffgsvk_safe as fits_read_subset_int;
    pub(crate) use ffgsvsb_safe as fits_read_subset_sbyt;
    pub(crate) use ffgsvui_safe as fits_read_subset_usht;
    pub(crate) use ffgsvuj_safe as fits_read_subset_ulng;
    pub(crate) use ffgsvujj_safe as fits_read_subset_ulnglng;
    pub(crate) use ffgsvuk_safe as fits_read_subset_uint;
    pub(crate) use ffgtbb_safe as fits_read_tblbytes;
    pub(crate) use ffgtcl_safe as fits_get_coltype;
    pub(crate) use ffgtclll_safe as fits_get_coltypell;
    pub(crate) use ffgtdm_safe as fits_read_tdim;
    pub(crate) use ffgthd_safe as fits_parse_templat;
    pub(crate) use ffhdef_safe as fits_set_hdrsize;
    pub(crate) use ffhdr2str_safe as fits_hdr2str;
    pub(crate) use fficls_safe as fits_insert_cols;
    pub(crate) use fficol_safe as fits_insert_col;
    pub(crate) use ffiimg_safer as fits_insert_img;
    pub(crate) use ffiimgll_safer as fits_insert_imgll;
    pub(crate) use ffikey_safe as fits_insert_card;
    pub(crate) use ffikyj_safe as fits_insert_key_lng;
    pub(crate) use ffinit_safer as fits_create_file;
    pub(crate) use ffirec_safe as fits_insert_record;
    pub(crate) use ffirow_safe as fits_insert_rows;
    pub(crate) use ffmahd_safe as fits_movabs_hdu;
    pub(crate) use ffmcom_safe as fits_modify_comment;
    pub(crate) use ffmcrd_safe as fits_modify_card;
    pub(crate) use ffmkfc_safe as fits_modify_key_fixcm;
    pub(crate) use ffmkfm_safe as fits_modify_key_fixdblcm;
    pub(crate) use ffmkky_safe as fits_make_key;
    pub(crate) use ffmkls_safe as fits_modify_key_longstr;
    pub(crate) use ffmkyc_safe as fits_modify_key_cmp;
    pub(crate) use ffmkyd_safe as fits_modify_key_dbl;
    pub(crate) use ffmkye_safe as fits_modify_key_flt;
    pub(crate) use ffmkyf_safe as fits_modify_key_fixfl;
    pub(crate) use ffmkyg_safe as fits_modify_key_fixdb;
    pub(crate) use ffmkyj_safe as fits_modify_key_lng;
    pub(crate) use ffmkyl_safe as fits_modify_key_log;
    pub(crate) use ffmkym_safe as fits_modify_key_dblcm;
    pub(crate) use ffmkys_safe as fits_modify_key_str;
    pub(crate) use ffmkyu_safe as fits_modify_key_null;
    pub(crate) use ffmnam_safe as fits_modify_name;
    pub(crate) use ffmnhd_safe as fits_movnam_hdu;
    pub(crate) use ffmrec_safe as fits_modify_record;
    pub(crate) use ffmrhd_safe as fits_movrel_hdu;
    pub(crate) use ffmvec_safe as fits_modify_vector_len;
    pub(crate) use ffnkey_safe as fits_make_nkey;
    pub(crate) use ffp2db_safe as fits_write_2d_byt;
    pub(crate) use ffp2dd_safe as fits_write_2d_dbl;
    pub(crate) use ffp2de_safe as fits_write_2d_flt;
    pub(crate) use ffp2di_safe as fits_write_2d_sht;
    pub(crate) use ffp2dj_safe as fits_write_2d_lng;
    pub(crate) use ffp2djj_safe as fits_write_2d_lnglng;
    pub(crate) use ffp2dk_safe as fits_write_2d_int;
    pub(crate) use ffp2dsb_safe as fits_write_2d_sbyt;
    pub(crate) use ffp2dui_safe as fits_write_2d_usht;
    pub(crate) use ffp2duj_safe as fits_write_2d_ulng;
    pub(crate) use ffp2dujj_safe as fits_write_2d_ulnglng;
    pub(crate) use ffp2duk_safe as fits_write_2d_uint;
    pub(crate) use ffp3db_safe as fits_write_3d_byt;
    pub(crate) use ffp3dd_safe as fits_write_3d_dbl;
    pub(crate) use ffp3de_safe as fits_write_3d_flt;
    pub(crate) use ffp3di_safe as fits_write_3d_sht;
    pub(crate) use ffp3dj_safe as fits_write_3d_lng;
    pub(crate) use ffp3djj_safe as fits_write_3d_lnglng;
    pub(crate) use ffp3dk_safe as fits_write_3d_int;
    pub(crate) use ffp3dsb_safe as fits_write_3d_sbyt;
    pub(crate) use ffp3dui_safe as fits_write_3d_usht;
    pub(crate) use ffp3duj_safe as fits_write_3d_ulng;
    pub(crate) use ffp3dujj_safe as fits_write_3d_ulnglng;
    pub(crate) use ffp3duk_safe as fits_write_3d_uint;
    pub(crate) use ffpcl_safer as fits_write_col;
    pub(crate) use ffpclb_safe as fits_write_col_byt;
    pub(crate) use ffpclc_safe as fits_write_col_cmp;
    pub(crate) use ffpcld_safe as fits_write_col_dbl;
    pub(crate) use ffpcle_safe as fits_write_col_flt;
    pub(crate) use ffpcli_safe as fits_write_col_sht;
    pub(crate) use ffpclj_safe as fits_write_col_lng;
    pub(crate) use ffpcljj_safe as fits_write_col_lnglng;
    pub(crate) use ffpclk_safe as fits_write_col_int;
    pub(crate) use ffpcll_safe as fits_write_col_log;
    pub(crate) use ffpclm_safe as fits_write_col_dblcmp;
    pub(crate) use ffpcls_safe as fits_write_col_str;
    pub(crate) use ffpclsb_safe as fits_write_col_sbyt;
    pub(crate) use ffpclu_safe as fits_write_col_null;
    pub(crate) use ffpclui_safe as fits_write_col_usht;
    pub(crate) use ffpcluj_safe as fits_write_col_ulng;
    pub(crate) use ffpclujj_safe as fits_write_col_ulnglng;
    pub(crate) use ffpcluk_safe as fits_write_col_uint;
    pub(crate) use ffpclx_safe as fits_write_col_bit;
    pub(crate) use ffpcn_safer as fits_write_colnul;
    pub(crate) use ffpcnb_safe as fits_write_colnull_by;
    pub(crate) use ffpcnd_safe as fits_write_colnull_db;
    pub(crate) use ffpcne_safe as fits_write_colnull_fl;
    pub(crate) use ffpcni_safe as fits_write_colnull_sh;
    pub(crate) use ffpcnj_safe as fits_write_colnull_ln;
    pub(crate) use ffpcnjj_safe as fits_write_colnull_lngln;
    pub(crate) use ffpcnk_safe as fits_write_colnull_in;
    pub(crate) use ffpcnl_safe as fits_write_colnull_lo;
    pub(crate) use ffpcns_safe as fits_write_colnull_st;
    pub(crate) use ffpcnsb_safe as fits_write_colnull_sby;
    pub(crate) use ffpcnui_safe as fits_write_colnull_ush;
    pub(crate) use ffpcnuj_safe as fits_write_colnull_uln;
    pub(crate) use ffpcnujj_safe as fits_write_colnull_ulngln;
    pub(crate) use ffpcnuk_safe as fits_write_colnull_uin;
    pub(crate) use ffpcom_safe as fits_write_comment;
    pub(crate) use ffpextn_safe as fits_write_ex;
    pub(crate) use ffpgpb_safe as fits_write_grppar_by;
    pub(crate) use ffpgpd_safe as fits_write_grppar_db;
    pub(crate) use ffpgpe_safe as fits_write_grppar_fl;
    pub(crate) use ffpgpi_safe as fits_write_grppar_sh;
    pub(crate) use ffpgpj_safe as fits_write_grppar_ln;
    pub(crate) use ffpgpjj_safe as fits_write_grppar_lngln;
    pub(crate) use ffpgpk_safe as fits_write_grppar_in;
    pub(crate) use ffpgpsb_safe as fits_write_grppar_sby;
    pub(crate) use ffpgpui_safe as fits_write_grppar_ush;
    pub(crate) use ffpgpuj_safe as fits_write_grppar_uln;
    pub(crate) use ffpgpujj_safe as fits_write_grppar_ulngln;
    pub(crate) use ffpgpuk_safe as fits_write_grppar_uin;
    pub(crate) use ffphis_safe as fits_write_history;
    pub(crate) use ffphpr_safe as fits_write_grphdr;
    pub(crate) use ffphprll_safe as fits_write_grphdrll;
    pub(crate) use ffphps_safe as fits_write_imghdr;
    pub(crate) use ffpkfc_safe as fits_write_key_fixcmp;
    pub(crate) use ffpkfm_safe as fits_write_key_fixdblcm;
    pub(crate) use ffpkls_safe as fits_write_key_longstr;
    pub(crate) use ffpky_safe as fits_write_key;
    pub(crate) use ffpkyc_safe as fits_write_key_cmp;
    pub(crate) use ffpkyd_safe as fits_write_key_dbl;
    pub(crate) use ffpkye_safe as fits_write_key_flt;
    pub(crate) use ffpkyf_safe as fits_write_key_fixflt;
    pub(crate) use ffpkyg_safe as fits_write_key_fixdbl;
    pub(crate) use ffpkyj_safe as fits_write_key_lng;
    pub(crate) use ffpkyl_safe as fits_write_key_log;
    pub(crate) use ffpkym_safe as fits_write_key_dblcmp;
    pub(crate) use ffpkys_safe as fits_write_key_str;
    pub(crate) use ffpkyu_safe as fits_write_key_null;
    pub(crate) use ffpkyuj_safe as fits_write_key_ulng;
    pub(crate) use ffpmrk_safe as fits_write_errmark;
    pub(crate) use ffpmsg_safer as fits_write_errmsg;
    pub(crate) use ffppn_safe as fits_write_imgnull;
    pub(crate) use ffppnb_safe as fits_write_imgnull_by;
    pub(crate) use ffppnd_safe as fits_write_imgnull_db;
    pub(crate) use ffppne_safe as fits_write_imgnull_fl;
    pub(crate) use ffppni_safe as fits_write_imgnull_sh;
    pub(crate) use ffppnj_safe as fits_write_imgnull_ln;
    pub(crate) use ffppnjj_safe as fits_write_imgnull_lngln;
    pub(crate) use ffppnk_safe as fits_write_imgnull_in;
    pub(crate) use ffppnsb_safe as fits_write_imgnull_sby;
    pub(crate) use ffppnui_safe as fits_write_imgnull_ush;
    pub(crate) use ffppnuj_safe as fits_write_imgnull_uln;
    pub(crate) use ffppnujj_safe as fits_write_imgnull_ulngln;
    pub(crate) use ffppnuk_safe as fits_write_imgnull_uin;
    pub(crate) use ffppr_safe as fits_write_img;
    pub(crate) use ffpprb_safe as fits_write_img_byt;
    pub(crate) use ffpprd_safe as fits_write_img_dbl;
    pub(crate) use ffppre_safe as fits_write_img_flt;
    pub(crate) use ffppri_safe as fits_write_img_sht;
    pub(crate) use ffpprj_safe as fits_write_img_lng;
    pub(crate) use ffpprjj_safe as fits_write_img_lnglng;
    pub(crate) use ffpprk_safe as fits_write_img_int;
    pub(crate) use ffpprn_safe as fits_write_null_im;
    pub(crate) use ffpprsb_safe as fits_write_img_sbyt;
    pub(crate) use ffppru_safe as fits_write_img_nul;
    pub(crate) use ffpprui_safe as fits_write_img_usht;
    pub(crate) use ffppruj_safe as fits_write_img_ulng;
    pub(crate) use ffpprujj_safe as fits_write_img_ulnglng;
    pub(crate) use ffppruk_safe as fits_write_img_uint;
    pub(crate) use ffppx_safer as fits_write_pix;
    pub(crate) use ffppxll_safer as fits_write_pixll;
    pub(crate) use ffprec_safe as fits_write_record;
    pub(crate) use ffprwu_safe as fits_write_nulrows;
    pub(crate) use ffprwu_safe as fits_write_nullrows;
    pub(crate) use ffpscl_safe as fits_set_bscale;
    pub(crate) use ffpss_safe as fits_write_subset;
    pub(crate) use ffpssb_safe as fits_write_subset_byt;
    pub(crate) use ffpssd_safe as fits_write_subset_dbl;
    pub(crate) use ffpsse_safe as fits_write_subset_flt;
    pub(crate) use ffpssi_safe as fits_write_subset_sht;
    pub(crate) use ffpssj_safe as fits_write_subset_lng;
    pub(crate) use ffpssjj_safe as fits_write_subset_lnglng;
    pub(crate) use ffpssk_safe as fits_write_subset_int;
    pub(crate) use ffpsssb_safe as fits_write_subset_sbyt;
    pub(crate) use ffpssui_safe as fits_write_subset_usht;
    pub(crate) use ffpssuj_safe as fits_write_subset_ulng;
    pub(crate) use ffpssujj_safe as fits_write_subset_ulnglng;
    pub(crate) use ffpssuk_safe as fits_write_subset_uint;
    pub(crate) use ffptbb_safe as fits_write_tblbytes;
    pub(crate) use ffrdef_safe as fits_set_hdustruc;
    pub(crate) use ffrsim_safe as fits_resize_img;
    pub(crate) use ffrsimll_safe as fits_resize_imgll;
    pub(crate) use ffrwrg_safe as fits_parse_range;
    pub(crate) use ffrwrgll_safe as fits_parse_rangell;
    pub(crate) use fftheap_safe as fits_test_heap;
    pub(crate) use fftkey_safe as fits_test_keyword;
    pub(crate) use fftrec_safe as fits_test_record;
    pub(crate) use ffucrd_safe as fits_update_card;
    pub(crate) use ffukfc_safe as fits_update_key_fixcm;
    pub(crate) use ffukfm_safe as fits_update_key_fixdblcm;
    pub(crate) use ffukls_safe as fits_update_key_longstr;
    pub(crate) use ffuky_safe as fits_update_key;
    pub(crate) use ffukyc_safe as fits_update_key_cmp;
    pub(crate) use ffukyd_safe as fits_update_key_dbl;
    pub(crate) use ffukye_safe as fits_update_key_flt;
    pub(crate) use ffukyf_safe as fits_update_key_fixfl;
    pub(crate) use ffukyg_safe as fits_update_key_fixdb;
    pub(crate) use ffukyj_safe as fits_update_key_lng;
    pub(crate) use ffukyl_safe as fits_update_key_log;
    pub(crate) use ffukym_safe as fits_update_key_dblcm;
    pub(crate) use ffukys_safe as fits_update_key_str;
    pub(crate) use ffukyu_safe as fits_update_key_null;
    pub(crate) use ffupch_safe as fits_uppercase;
    pub(crate) use ffvcks_safe as fits_verify_chksum;
}

#[deny(deprecated)]
pub(crate) mod safe {

    pub use super::*;

    pub(crate) use ffcmps_safe as fits_compare_str;
    pub(crate) use ffdtyp_safe as fits_get_keytype;
    pub(crate) use ffgerr_safe as fits_get_errstatus;
    pub(crate) use ffghdn_safe as fits_get_hdu_num;
    pub(crate) use ffghps_safe as fits_get_hdrpos;
    pub(crate) use ffghsp_safe as fits_get_hdrspace;
    pub(crate) use ffkeyn_safe as fits_make_keyn;
    pub(crate) use ffmaky_safe as fits_movabs_key;
    pub(crate) use ffmrky_safe as fits_movrel_key;
    pub(crate) use ffpsvc_safe as fits_parse_value;
    pub(crate) use fftscl_safe as fits_set_tscale;

    pub(crate) use ffchtps as fits_cleanup_https;
    pub(crate) use ffihtps as fits_init_https;
    pub(crate) use ffshdwn as fits_show_download_progress;
    pub(crate) use ffvhtps as fits_verbose_https;
}

#[deny(unsafe_code, unsafe_op_in_unsafe_fn, deprecated)]
mod unknown {
    pub use super::*;

    // pub use ffbinr as fits_parse_binrang;
    // pub use ffbins as fits_parse_binspec;
    // pub use ffourl as fits_parse_output_url;
    // pub use ffdt2s as fits_date2str;
    // pub use ffgsdt as fits_get_system_date;
    // pub use ffphext as fits_write_exthdr;
    // pub use ffphpsll as fits_write_imghdrll;
    // pub use ffptdmll as fits_write_tdimll;
    // pub use ffs2dt as fits_str2date;
    // pub use ffs2tm as fits_str2time;
    // pub use fftm2s as fits_time2str;
    // pub use fits_comp_img as fits_compress_im;
    // pub use fits_decomp_img as fits_decompress_im;
    // pub use ffgcxui as fits_read_col_bit_ush;
    // pub use ffgcxuk as fits_read_col_bit_uin;
    // pub use ffcrow as fits_calc_rows;
    // pub use fffrwc as fits_find_rows_cmp;
    // pub use ffsrow as fits_select_rows;
    // pub use fftexp as fits_test_expr;
    // pub use ffgtam as fits_add_group_member;
    // pub use ffgtch as fits_change_group;
    // pub use ffgtcm as fits_compact_group;
    // pub use ffgtcp as fits_copy_group;
    // pub use ffgtcr as fits_create_group;
    // pub use ffgtis as fits_insert_group;
    // pub use ffgtmg as fits_merge_groups;
    // pub use ffgtnm as fits_get_num_members;
    // pub use ffgtop as fits_open_group;
    // pub use ffgtrm as fits_remove_group;
    // pub use ffgtvf as fits_verify_group;
    // pub use ffgmcp as fits_copy_member;
    // pub use ffgmng as fits_get_num_groups;
    // pub use ffgmop as fits_open_member;
    // pub use ffgmrm as fits_remove_member;
    // pub use ffgmtf as fits_transfer_member;
}
