name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Temporarily modify the rust toolchain version
      run: rustup override set nightly-2025-04-25
    - name: Output rust version for educational purposes
      run: rustup --version

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run testprog checks
      run: bash ./testprog_check.sh
